---
name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Linting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'
      - run: go fmt